require 'rubygems'
require 'active_record'
require 'logger'
require 'yaml'

config = YAML.load_file('config/database.yml')

ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.establish_connection(config["db"]["development"])

task :migrate do
  ActiveRecord::Migrator.migrate('db/migrate', ENV["VERSION"] ? ENV["VERSION"].to_i : nil)
end

